### ISSUE TITLE
Gitsense failed to load

### ISSUE THREAD

**Issue by JobaDiniz** [gitsense/vsts-ext#3]
GitSense by GitSense failed to load.Learn More about this extension, including available support options.
Failed to load script: http://my-server.intranet.local:8080/tfs/_static/3rdParty/_scripts/jquery.xdomainrequest.min.js

_VSS.SDK.min.js:4 Mixed Content: The page at 'https://public.gitsense.com/insight?vte=true&hub=true' was loaded over HTTPS, but requested an insecure script 'http://my-server.intranet.local:8080/tfs/_static/3rdParty/_scripts/jquery.xdomainrequest.min.js'. This request has been blocked; the content must be served over HTTPS._

**Comment by gitsense** [comment]
The extension is complaining because the public GitSense server is secured, but your TFS server is not.   As a side note, GitSense is currently on hold for a year or two, so there will be no support.  Thanks for your interest though.
