### ISSUE TITLE
Azure DevOps Repos - "GitSense is taking longer than expected to load"

### ISSUE THREAD

**Issue by bveselka** [gitsense/vsts-ext#4]
I have added the GitSense plugin for Azure DevOps Repos.  When I click the GitSense link, it refuses to load and I only get a message of "GitSense is taking longer than expected to load".  I have no other error messages pointing to an issue on my end.

**Comment by gitsense** [comment]
Sorry,  Gitsense development is currently on hold and is currently not supported.

Thanks for trying the extension though.

**Comment by SeletskySergey** [comment]
same issue

**Comment by chrisaddams** [comment]
boo-hiss... maybe remove it from the marketplace?
